alter table public.admin
  add column if not exists status text not null default 'active',
  add column if not exists archive_reason text,
  add column if not exists archived_at timestamptz;

create or replace function public.is_lyft_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.admin as admin_user
    where admin_user.clerk_id = (select auth.jwt() ->> 'sub')
      and admin_user.role in ('super_admin', 'verifier', 'support', 'finance')
      and admin_user.status = 'active'
  );
$$;

revoke all on function public.is_lyft_admin() from public;
grant execute on function public.is_lyft_admin() to authenticated;

create or replace function public.is_lyft_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.admin as admin_user
    where admin_user.clerk_id = (select auth.jwt() ->> 'sub')
      and admin_user.role = 'super_admin'
      and admin_user.status = 'active'
  );
$$;

revoke all on function public.is_lyft_super_admin() from public;
grant execute on function public.is_lyft_super_admin() to authenticated;

create or replace function public.is_safety_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.admin as admin_user
    where admin_user.clerk_id = (select auth.jwt() ->> 'sub')
      and admin_user.status = 'active'
      and admin_user.role in ('super_admin', 'support')
  );
$$;

revoke all on function public.is_safety_admin() from public;
grant execute on function public.is_safety_admin() to authenticated;

alter table public.admin enable row level security;
revoke all on table public.admin from anon, authenticated, public;
grant select, delete on table public.admin to authenticated;
grant update (status, archive_reason, archived_at) on table public.admin to authenticated;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname from pg_policies where schemaname = 'public' and tablename = 'admin'
  loop
    execute format('drop policy %I on public.admin', existing_policy.policyname);
  end loop;
end
$$;

create policy "Users can read their own admin profile"
  on public.admin
  for select
  to authenticated
  using (clerk_id = (select auth.jwt() ->> 'sub') or public.is_lyft_super_admin());

create policy "Super admins can update admin account status"
  on public.admin
  for update
  to authenticated
  using (public.is_lyft_super_admin())
  with check (public.is_lyft_super_admin());

create policy "Super admins can delete admin accounts"
  on public.admin
  for delete
  to authenticated
  using (public.is_lyft_super_admin());

create table if not exists public.admin_app_settings (
  key text primary key,
  value jsonb not null,
  updated_by text not null,
  updated_at timestamptz not null default now()
);

alter table public.admin_app_settings enable row level security;
revoke all on table public.admin_app_settings from anon, authenticated, public;
grant select, insert, update on table public.admin_app_settings to authenticated;

drop policy if exists "Admins can read admin app settings" on public.admin_app_settings;
create policy "Admins can read admin app settings"
  on public.admin_app_settings
  for select
  to authenticated
  using (public.is_lyft_admin());

drop policy if exists "Admins can insert admin app settings" on public.admin_app_settings;
create policy "Admins can insert admin app settings"
  on public.admin_app_settings
  for insert
  to authenticated
  with check (public.is_lyft_admin() and updated_by = (select auth.jwt() ->> 'sub'));

drop policy if exists "Admins can update admin app settings" on public.admin_app_settings;
create policy "Admins can update admin app settings"
  on public.admin_app_settings
  for update
  to authenticated
  using (public.is_lyft_admin())
  with check (public.is_lyft_admin() and updated_by = (select auth.jwt() ->> 'sub'));

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_clerk_id text not null,
  admin_name text not null,
  admin_role text not null,
  action text not null,
  target text not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_admin_audit_actor()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor public.admin%rowtype;
begin
  select * into actor
  from public.admin
  where clerk_id = (select auth.jwt() ->> 'sub')
    and status = 'active';

  if not found then
    raise exception 'An active admin account is required to write audit history';
  end if;

  new.admin_clerk_id := actor.clerk_id;
  new.admin_name := coalesce(actor.full_name, actor.email, actor.clerk_id);
  new.admin_role := actor.role;
  return new;
end;
$$;

revoke all on function public.set_admin_audit_actor() from public;

drop trigger if exists set_admin_audit_actor on public.admin_audit_log;
create trigger set_admin_audit_actor
  before insert on public.admin_audit_log
  for each row execute function public.set_admin_audit_actor();

alter table public.admin_audit_log enable row level security;
revoke all on table public.admin_audit_log from anon, authenticated, public;
grant select, insert on table public.admin_audit_log to authenticated;
grant usage, select on sequence public.admin_audit_log_id_seq to authenticated;

drop policy if exists "Admins can read audit history" on public.admin_audit_log;
create policy "Admins can read audit history"
  on public.admin_audit_log
  for select
  to authenticated
  using (public.is_lyft_admin());

drop policy if exists "Admins can append their own audit events" on public.admin_audit_log;
create policy "Admins can append their own audit events"
  on public.admin_audit_log
  for insert
  to authenticated
  with check (
    public.is_lyft_admin()
    and admin_clerk_id = (select auth.jwt() ->> 'sub')
    and admin_role in ('super_admin', 'verifier', 'support', 'finance')
  );
